spring:
  jpa:
    show-sql: true
    open-in-view: 'false'
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: 'TRUE'
        search:
          backend:
            analysis:
              configurer: com.novara.novara_demo.config.hibernate_search.CompositeAnalysisConfigurer
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
  boot:
    admin:
      client:
        url: http://localhost:8081
        auto-registration: true
        auto-deregistration: true
        instance-auth:
          enabled: true
        period: 30000
        username: user
        password: pass
  datasource:
    username: ${MYSQL_USERNAME1:root}
    url: jdbc:mysql://localhost:3306/novara-user-test?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
    driverClassName: com.mysql.cj.jdbc.Driver
    password: ${MYSQL_PASS1:1q2w3e4r}
    default.admin.pass: ${DEFAULT_ADMIN_PASS}

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.arm.jdbc.bind: ERROR
    org.springframework: ERROR
    org.springframework.boot.actuate: ERROR
#    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    org.springframework.security: ERROR

server:
  port: 8095

app:
  jwt:
    issuer: "novara-demo-api"
    secret: "${APP_JWT_SECRET:change-me-please-change-me-please-32b-min}"
    expiry-minutes: 10
    refresh-expiry-hours: 24

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /manage
  endpoint:
    health:
      show-details: when_authorized

info:
  app:
    name: Demo Spring API
    version: 0.9